config/routes.rb
Rails.application.routes.draw do
  resources :participacoes
  devise_for :users
  resources :boloes do
    get 'define' => 'boloes#define'
    post 'define' => 'boloes#save_definition'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bolao.rb
class Bolao < ApplicationRecord
  has_many :palpite
end

app/models/escolha.rb
class Escolha < ApplicationRecord
  belongs_to :participacao
  belongs_to :palpite
  belongs_to :opcao
end

app/models/opcao.rb
class Opcao < ApplicationRecord
  belongs_to :palpite
end

app/models/palpite.rb
class Palpite < ApplicationRecord
  alias_attribute :opcoes, :opcao

  belongs_to :bolao
  has_many :opcao

  def self.clear(bolao_id)
    palpites = Palpite.where(bolao_id: bolao_id)
    palpites.each do |palpite|
      opcoes = Opcao.where(palpite_id: palpite.id)
      opcoes.each do |opcao|
        opcao.destroy
      end
      palpite.destroy
    end
  end
end

app/models/participacao.rb
class Participacao < ApplicationRecord
  belongs_to :user
  belongs_to :bolao
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boloes_controller.rb
class BoloesController < ApplicationController
  before_action :set_bolao, only: [:show, :edit, :update, :destroy]
  before_action :set_bolao_define, only: [:define, :save_definition]

  # GET /boloes
  # GET /boloes.json
  def index
    @boloes = Bolao.all
  end

  # GET /boloes/1
  # GET /boloes/1.json
  def show
  end

  # GET /boloes/new
  def new
    @bolao = Bolao.new
  end

  # GET /boloes/1/edit
  def edit
  end

  # POST /boloes
  # POST /boloes.json
  def create
    @bolao = Bolao.new(bolao_params)

    respond_to do |format|
      if @bolao.save
        format.html { redirect_to @bolao, notice: 'Bolao was successfully created.' }
        format.json { render :show, status: :created, location: @bolao }
      else
        format.html { render :new }
        format.json { render json: @bolao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boloes/1
  # PATCH/PUT /boloes/1.json
  def update
    respond_to do |format|
      if @bolao.update(bolao_params)
        format.html { redirect_to @bolao, notice: 'Bolao was successfully updated.' }
        format.json { render :show, status: :ok, location: @bolao }
      else
        format.html { render :edit }
        format.json { render json: @bolao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boloes/1
  # DELETE /boloes/1.json
  def destroy
    @bolao.destroy
    respond_to do |format|
      format.html { redirect_to boloes_url, notice: 'Bolao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /boloes/1/define
  def define
    @palpites = Palpite.where(bolao_id: @bolao.id)
  end

  # POST /boloes/1/define
  def save_definition
    respond_to do |format|
      Palpite.clear(@bolao.id)
      params[:palpites].each do |palpite|
        palpite_db = Palpite.create(pergunta: palpite[:pergunta], tipo: palpite[:tipo], bolao_id: @bolao.id)
        if palpite_db
          palpite[:opcoes].each do |opcao|
            Opcao.create(valor: opcao[:valor], correta: opcao.try(:[], :correta), palpite_id: palpite_db.id)
          end

          format.html { redirect_to bolao_define_url(@bolao), notice: 'Bolao was successfully destroyed.' }
          format.json { head :no_content }
        else
          format.html { redirect_to bolao_define_url(@bolao), notice: 'Bolao was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bolao
      @bolao = Bolao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bolao_params
      params.require(:bolao).permit(:nome, :ativo)
    end

    def set_bolao_define
      @bolao = Bolao.find(params[:bolao_id])
    end

    def bolao_define_params
      params.require(:palpites).permit()
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @boloes = Bolao.all
  end
end

app/controllers/participacoes_controller.rb
class ParticipacoesController < ApplicationController
  before_action :set_participacao, only: [:show, :edit, :update, :destroy]
  before_action :set_bolao, only: [:new]
  before_action :authenticate_user!

  # GET /participacoes
  # GET /participacoes.json
  def index
    @participacoes = Participacao.all
  end

  # GET /participacoes/1
  # GET /participacoes/1.json
  def show
  end

  # GET /participacoes/new
  def new
    @participacao = Participacao.new
  end

  # GET /participacoes/1/edit
  def edit
    @bolao = @participacao.bolao
  end

  # POST /participacoes
  # POST /participacoes.json
  def create
    @participacao = Participacao.new(participacao_params)

    respond_to do |format|
      if @participacao.save
        params[:escolhas].each do |palpite_id, opcao_id|
          Escolha.create(participacao_id: @participacao.id, palpite_id: palpite_id, opcao_id: opcao_id)
        end
        format.html { redirect_to @participacao, notice: 'Participacao was successfully created.' }
        format.json { render :show, status: :created, location: @participacao }
      else
        format.html { render :new }
        format.json { render json: @participacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participacoes/1
  # PATCH/PUT /participacoes/1.json
  def update
    respond_to do |format|
      if @participacao.update(participacao_params)
        format.html { redirect_to @participacao, notice: 'Participacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @participacao }
      else
        format.html { render :edit }
        format.json { render json: @participacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participacoes/1
  # DELETE /participacoes/1.json
  def destroy
    @participacao.destroy
    respond_to do |format|
      format.html { redirect_to participacoes_url, notice: 'Participacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participacao
      @participacao = Participacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participacao_params
      params.require(:participacao).permit(:user_id, :bolao_id)
    end

    def set_bolao
      @bolao = Bolao.find(params[:bolao_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boloes/_form.html.erb
<%= form_with(model: bolao, local: true) do |form| %>
  <% if bolao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bolao.errors.count, "error") %> prohibited this bolao from being saved:</h2>

      <ul>
      <% bolao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :nome, class: 'col-sm-2' %>
    <div class="col-sm-10">
      <%= form.text_field :nome, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :ativo, class: 'col-sm-2' %>
    <div class="col-sm-10">
      <%= form.check_box :ativo %>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= form.submit 'Salvar', class: 'btn btn-success m-1' %>
    <%= link_to 'Voltar', boloes_path, class: 'btn btn-primary m-1' %>
  </div>
<% end %>

app/views/boloes/_form_palpites.html.erb
<%= form_tag bolao_define_path(bolao), id: 'formu', method: :post do %>
  <% if bolao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bolao.errors.count, "error") %> prohibited this bolao from being saved:</h2>

      <ul>
      <% bolao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag 'bolao[nome]', bolao.nome %>
  <%= hidden_field_tag 'bolao[ativo]', bolao.ativo %>

  <div id="palpites">
    <% @palpites.each_with_index do |palpite, i| %>
      <%= render 'template_palpite', template: false, palpite: palpite, i: i %>
    <% end %>
  </div>

  <div class="d-flex justify-content-center">
    <a href="#" class="btn btn-info m-1 add-palpite-btn">Adicionar Pergunta</a>
    <%= submit_tag 'Salvar Perguntas', class: 'btn btn-success m-1' %>
    <%= link_to 'Voltar', boloes_path, class: 'btn btn-primary m-1' %>
  </div>
<% end %>

<!-- Template Opções -->
<template id="template-opcao">
  <%= render 'template_opcao', template: true %>
</template>

<template id="template-palpite">
  <%= render 'template_palpite', template: true %>
</template>

app/views/boloes/_template_opcao.html.erb
<% if template %>
  <% opcao_id = 'OPCAO_ID' %>
  <% opcao = {palpite: {id: "local_#{rand(100)}"}, valor: '', correta: false} %>
<% else %>
  <% opcao_id = "#{j+1}" %>
<% end %>
<div class="opcao">
  <div class="form-group row">
    <label for="opcao_<%= opcao.try(:palpite).try(:id) %>_<%= opcao_id %>_valor" class="col-sm-2">Opção <%= opcao_id %>:</label>
    <div class="col-sm-4">
      <input type="text" value="<%= opcao[:valor] %>" name="palpites[][opcoes][][valor]" id="opcao_<%= opcao.try(:palpite).try(:id) %>_<%= opcao_id %>_valor" class="form-control">
    </div>
    <label for="opcao_<%= opcao.try(:palpite).try(:id) %>_<%= opcao_id %>_correta" class="col-sm-2">Correta?:</label>
    <div class="col-sm-4">
      <input type="checkbox" <%= "checked" if opcao[:correta] %> id="opcao_<%= opcao.try(:palpite).try(:id) %>_<%= opcao_id %>_correta" name="palpites[][opcoes][][correta]">
    </div>
  </div>
</div>

app/views/boloes/_template_palpite.html.erb
<% if template %>
  <% palpite_id = 'PALPITE_ID' %>
  <% palpite = {pergunta: '', opcoes: []} %>
<% else %>
  <% palpite_id = "#{i+1}" %>
<% end %>
<div class="palpite">
  <div class="form-group row">
    <label for="palpite_<%= palpite_id %>_pergunta" class="col-sm-2">Pergunta:</label>
    <div class="col-sm-10">
      <input type="text" value="<%= palpite[:pergunta] %>" id="palpite_<%= palpite_id %>_pergunta" name="palpites[][pergunta]" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="palpite_<%= palpite_id %>_tipo" class="col-sm-2">Tipo:</label>
    <div class="col-sm-10">
      <select id="palpite_<%= palpite_id %>_tipo" name="palpites[][tipo]" class="form-control">
        <option value="checkbox">Checkbox</option>
        <option value="radio">Radio</option>
        <!-- <option value="text">Texto</option> -->
      </select>
    </div>
  </div>
  
  <div class="wrapper">
    <div class="opcoes">
      <% palpite.try(:opcoes).try(:each_with_index) do |opcao, j| %>
        <%= render 'template_opcao', template: false, opcao: opcao, j: j %>
      <% end %>
    </div>

    <div class="container d-flex justify-content-center">
      <button type="button" class="btn btn-info m-1 add-opcao-btn">Adicionar Opção</button>
      <button type="button" href="#" class="btn btn-warning m-1 rem-opcao-btn">Remover Opção</button>
      <button type="button" href="#" class="btn btn-danger m-1 rem-palpite-btn">Remover Pergunta</button>
    </div>
  </div>
  <hr>
</div>

app/views/boloes/define.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Definir o bolão
  </div>
  <div class="card-body">
    <%= render 'form_palpites', bolao: @bolao %>
  </div>
</div>

app/views/boloes/edit.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Editar bolão
  </div>
  <div class="card-body">
    <%= render 'form', bolao: @bolao %>
  </div>
</div>

app/views/boloes/index.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Bolões
  </div>
  <div class="card-body">
    <table class="table">
      <thead class="thead-dark">
        <th>#</th>
        <th>Nome</th>
        <th colspan="2">Ações</th>
      </thead>
      <tbody>
        <% @boloes.each do |bolao| %>
          <tr>
            <td><%= bolao.id %></td>
            <td><%= bolao.nome %></td>
            <td><%= link_to 'Visualizar', bolao_path(bolao) %></td>
            <td><%= link_to 'Editar', edit_bolao_path(bolao) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= link_to 'Novo', new_bolao_path, class: 'btn btn-success m-1' %>
    </div>
  </div>
</div>

app/views/boloes/new.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Novo bolão
  </div>
  <div class="card-body">
    <%= render 'form', bolao: @bolao %>
  </div>
</div>

app/views/boloes/show.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Bolão
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-2">
        <strong>Nome:</strong>
      </div>
      <div class="col-sm-10">
        <%= @bolao.nome %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <strong>Ativo:</strong>
      </div>
      <div class="col-sm-10">
        <%= @bolao.ativo %>
      </div>
    </div>

    <div class="d-flex justify-content-center">
      <%= link_to 'Editar', edit_bolao_path(@bolao), class: 'btn btn-success m-1' %>
      <%= link_to 'Voltar', boloes_path, class: 'btn btn-primary m-1' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Bolões
  </div>
  <div class="card-body">
    <table class="table">
      <thead class="thead-dark">
        <th>#</th>
        <th colspan="3">Nome</th>
        <th>Ações</th>
      </thead>
      <tbody>
        <% @boloes.each do |bolao| %>
          <tr>
            <td><%= bolao.id %></td>
            <td colspan="3"><%= bolao.nome %></td>
            <td><%= link_to 'Participar', {controller: 'participacoes', action: 'new', bolao_id: bolao.id } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BolaoGot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="main-nav" class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container d-flex justify-content-center">
        <a href="<%= root_path %>" class="navbar-brand">Bolão</a>
      </div>
    </nav>

    <main class="container">
      <br>
      <% if notice %>
        <div class="alert alert-success m1" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/participacoes/_form.html.erb
<%= form_with(model: participacao, local: true) do |form| %>
  <% if participacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participacao.errors.count, "error") %> prohibited this participacao from being saved:</h2>

      <ul>
      <% participacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag 'participacao[user_id]', current_user.id %>
  <%= hidden_field_tag 'participacao[bolao_id]', params[:bolao_id] %>

  <div class="container">
    <% @bolao.palpite.each do |palpite| %>
      <div class="row">
        <h5><%= palpite.pergunta %></h5>
      </div>
      <div class="row">
        <% palpite.opcoes.each do |opcao| %>
          <div class="form-group form-check">
            <input type="<%= palpite.tipo %>" value="<%= opcao.id %>" id="<%= palpite.id %>_<%= opcao.id %>" name="escolhas[<%= palpite.id %>]" />
            <label for="<%= palpite.id %>_<%= opcao.id %>"><%= opcao.valor %></label><br>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-center">
    <%= form.submit 'Salvar', class: 'btn btn-success m-1' %>
  </div>
<% end %>

app/views/participacoes/edit.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Editar participação
  </div>
  <div class="card-body">
    <%= render 'form', participacao: @participacao %>
  </div>
</div>

app/views/participacoes/index.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Participações
  </div>
  <div class="card-body">
    <table class="table">
      <thead class="thead-dark">
        <th>Bolão</th>
        <th colspan="2">Ações</th>
      </thead>
      <tbody>
        <% @participacoes.each do |participacao| %>
          <tr>
            <td><%= participacao.bolao.nome %></td>
            <td><%= link_to 'Visualizar', participacao_path(participacao) %></td>
            <td><%= link_to 'Editar', edit_participacao_path(participacao) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= link_to 'Novo', new_participacao_path, class: 'btn btn-success m-1' %>
    </div>
  </div>
</div>

app/views/participacoes/new.html.erb
<div class="card">
  <div class="card-header d-flex justify-content-center">
    Nova participação
  </div>
  <div class="card-body">
    <%= render 'form', participacao: @participacao %>
  </div>
</div>

app/views/participacoes/show.html.erb
<!-- <div class="card">
  <div class="card-header d-flex justify-content-center">
    Bolão
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-2">
        <strong>Nome:</strong>
      </div>
      <div class="col-sm-10">
        <%= @bolao.nome %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <strong>Ativo:</strong>
      </div>
      <div class="col-sm-10">
        <%= @bolao.ativo %>
      </div>
    </div>

    <div class="d-flex justify-content-center">
      <%= link_to 'Editar', edit_bolao_path(@bolao), class: 'btn btn-success m-1' %>
      <%= link_to 'Voltar', boloes_path, class: 'btn btn-primary m-1' %>
    </div>
  </div>
</div> -->
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @participacao.user %>
</p>

<p>
  <strong>Bolao:</strong>
  <%= @participacao.bolao %>
</p>

<%= link_to 'Edit', edit_participacao_path(@participacao) %> |
<%= link_to 'Back', participacoes_path %>